/*
============================================================
BANKING CUSTOMER & TRANSACTION ANALYTICS
SQL ANALYSIS
============================================================

Database: PostgreSQL
Dataset: Synthetic Banking Dataset
Period: January 1, 2025 - December 31, 2025
Currency: INR

Purpose:
Analyze customer demographics, customer activity,
transaction behavior, account types, and product adoption.

Author: Anita R
============================================================
*/


/*
============================================================
SECTION 1: KEY PERFORMANCE INDICATORS (KPIs)
============================================================
*/


-- Query 1: Total Customers
-- Business Question:
-- How many customers are present in the banking dataset?

SELECT
    COUNT(*) AS total_customers
FROM customers;


-- Query 2: Active Customers
-- Business Definition:
-- A customer is considered active if they have at least
-- one transaction during 2025.

SELECT
    COUNT(DISTINCT a.customer_id) AS active_customers
FROM accounts a
JOIN transactions t
    ON a.account_id = t.account_id;


-- Query 3: Total Transactions
-- Business Question:
-- How many transactions occurred during the analysis period?

SELECT
    COUNT(*) AS total_transactions
FROM transactions;


-- Query 4: Total Transaction Value
-- Business Question:
-- What is the total value of all transactions?

SELECT
    ROUND(SUM(amount), 2) AS total_transaction_value
FROM transactions;


-- Query 5: Average Transaction Value
-- Business Question:
-- What is the average value of a transaction?

SELECT
    ROUND(AVG(amount), 2) AS average_transaction_value
FROM transactions;


/*
============================================================
SECTION 2: CUSTOMER ANALYSIS
============================================================
*/


-- Query 6: Customers by Segment
-- Business Question:
-- How is the customer base distributed across segments?

SELECT
    segment,
    COUNT(*) AS customer_count
FROM customers
GROUP BY segment
ORDER BY customer_count DESC;


-- Query 7: Customers by City
-- Business Question:
-- Which cities have the largest customer populations?

SELECT
    city,
    COUNT(*) AS customer_count
FROM customers
GROUP BY city
ORDER BY customer_count DESC;


-- Query 8: Customers by Age Group
-- Business Question:
-- How is the customer base distributed by age group?

SELECT
    age_group,
    COUNT(*) AS customer_count
FROM customers
GROUP BY age_group
ORDER BY customer_count DESC;


-- Query 9: Customer Distribution by Segment and Age Group
-- Business Question:
-- How are different age groups distributed within
-- each customer segment?

SELECT
    segment,
    age_group,
    COUNT(*) AS customer_count
FROM customers
GROUP BY
    segment,
    age_group
ORDER BY
    segment,
    customer_count DESC;


-- Query 10: Average Age by Customer Segment
-- Business Question:
-- What is the average age of customers in each segment?

SELECT
    segment,
    ROUND(AVG(age), 1) AS average_age,
    COUNT(*) AS customer_count
FROM customers
GROUP BY segment
ORDER BY average_age;


/*
============================================================
SECTION 3: CUSTOMER ACTIVITY & SEGMENT ANALYSIS
============================================================
*/


-- Query 11: Active Customers by Segment
-- Business Question:
-- How many customers in each segment are actively
-- using their accounts?

SELECT
    c.segment,
    COUNT(DISTINCT c.customer_id) AS active_customers
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.segment
ORDER BY active_customers DESC;


-- Query 12: Transaction Count by Customer Segment
-- Business Question:
-- How many transactions are generated by each
-- customer segment?

SELECT
    c.segment,
    COUNT(t.transaction_id) AS transaction_count
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.segment
ORDER BY transaction_count DESC;


-- Query 13: Transaction Value by Customer Segment
-- Business Question:
-- What is the total transaction value generated
-- by each customer segment?

SELECT
    c.segment,
    ROUND(SUM(t.amount), 2) AS total_transaction_value
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.segment
ORDER BY total_transaction_value DESC;


-- Query 14: Average Transaction Value by Segment
-- Business Question:
-- Does transaction size differ significantly across
-- customer segments?

SELECT
    c.segment,
    ROUND(AVG(t.amount), 2) AS average_transaction_value,
    COUNT(t.transaction_id) AS transaction_count
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.segment
ORDER BY average_transaction_value DESC;


/*
============================================================
SECTION 4: TRANSACTION ANALYSIS
============================================================
*/


-- Query 15: Monthly Transaction Trend
-- Business Question:
-- How does transaction volume and transaction value
-- change over the year?

SELECT
    transaction_month,
    COUNT(*) AS transaction_count,
    ROUND(SUM(amount), 2) AS transaction_value
FROM transactions
GROUP BY transaction_month
ORDER BY transaction_month;


-- Query 16: Debit vs Credit Transactions
-- Business Question:
-- How do debit and credit transactions compare
-- in volume and value?

SELECT
    transaction_type,
    COUNT(*) AS transaction_count,
    ROUND(SUM(amount), 2) AS transaction_value,
    ROUND(AVG(amount), 2) AS average_transaction_value
FROM transactions
GROUP BY transaction_type
ORDER BY transaction_count DESC;


-- Query 17: Transactions by Channel
-- Business Question:
-- Which transaction channels are used most frequently
-- and generate the highest transaction value?

SELECT
    channel,
    COUNT(*) AS transaction_count,
    ROUND(SUM(amount), 2) AS transaction_value,
    ROUND(AVG(amount), 2) AS average_transaction_value
FROM transactions
GROUP BY channel
ORDER BY transaction_count DESC;


-- Query 18: High-Value Transactions
-- Business Question:
-- How many transactions exceed the analytical
-- high-value threshold of ₹50,000?

SELECT
    COUNT(*) AS high_value_transactions,
    ROUND(SUM(amount), 2) AS high_value_transaction_value,
    ROUND(AVG(amount), 2) AS average_high_value_transaction
FROM transactions
WHERE amount > 50000;


-- Query 19: Largest Individual Transactions
-- Business Question:
-- Which individual transactions have the highest values?

SELECT
    transaction_id,
    account_id,
    transaction_date,
    transaction_type,
    amount,
    channel
FROM transactions
ORDER BY amount DESC
LIMIT 10;


/*
============================================================
SECTION 5: PRODUCT ANALYSIS
============================================================

IMPORTANT DATA MODEL NOTE:

The customer_products table identifies which products
customers have, but transactions do not contain product_id.

Therefore, transaction value should NOT be directly
attributed to products.

The following analysis focuses on product adoption
and customer activity associated with product ownership.
============================================================
*/


-- Query 20: Customers by Product
-- Business Question:
-- How many customers are associated with each product?

SELECT
    p.product_name,
    COUNT(DISTINCT cp.customer_id) AS customer_count
FROM customer_products cp
JOIN products p
    ON cp.product_id = p.product_id
GROUP BY p.product_name
ORDER BY customer_count DESC;


-- Query 21: Active Customers and Activity Rate by Product
-- Business Question:
-- What percentage of customers associated with each
-- product are active?

WITH product_customers AS (
    SELECT
        cp.product_id,
        COUNT(DISTINCT cp.customer_id) AS total_customers
    FROM customer_products cp
    GROUP BY cp.product_id
),

active_product_customers AS (
    SELECT
        cp.product_id,
        COUNT(DISTINCT cp.customer_id) AS active_customers
    FROM customer_products cp
    JOIN accounts a
        ON cp.customer_id = a.customer_id
    JOIN transactions t
        ON a.account_id = t.account_id
    GROUP BY cp.product_id
)

SELECT
    p.product_name,
    pc.total_customers,
    COALESCE(apc.active_customers, 0) AS active_customers,
    ROUND(
        COALESCE(apc.active_customers, 0) * 100.0
        / pc.total_customers,
        2
    ) AS activity_rate
FROM products p
JOIN product_customers pc
    ON p.product_id = pc.product_id
LEFT JOIN active_product_customers apc
    ON p.product_id = apc.product_id
ORDER BY activity_rate DESC;


/*
============================================================
SECTION 6: ACCOUNT TYPE ANALYSIS
============================================================
*/


-- Query 22: Transactions by Account Type
-- Business Question:
-- Which account types generate the highest transaction
-- volume and transaction value?

SELECT
    a.account_type,
    COUNT(t.transaction_id) AS transaction_count,
    ROUND(SUM(t.amount), 2) AS transaction_value,
    ROUND(AVG(t.amount), 2) AS average_transaction_value
FROM accounts a
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY a.account_type
ORDER BY transaction_count DESC;


-- Query 23: Account Type by Transaction Type
-- Business Question:
-- How do debit and credit transaction patterns
-- differ across account types?

SELECT
    a.account_type,
    t.transaction_type,
    COUNT(t.transaction_id) AS transaction_count,
    ROUND(SUM(t.amount), 2) AS transaction_value,
    ROUND(AVG(t.amount), 2) AS average_transaction_value
FROM accounts a
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY
    a.account_type,
    t.transaction_type
ORDER BY
    a.account_type,
    t.transaction_type;


/*
============================================================
SECTION 7: CUSTOMER-LEVEL ACTIVITY
============================================================
*/


-- Query 24: Top Customers by Transaction Activity
-- Business Question:
-- Which customers have the highest transaction frequency
-- and what is the value of their transactions?

SELECT
    c.customer_id,
    c.customer_name,
    c.segment,
    COUNT(t.transaction_id) AS transaction_count,
    ROUND(SUM(t.amount), 2) AS total_transaction_value,
    ROUND(AVG(t.amount), 2) AS average_transaction_value
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY
    c.customer_id,
    c.customer_name,
    c.segment
ORDER BY transaction_count DESC
LIMIT 10;


-- Query 25: Customer Activity Buckets
-- Business Question:
-- How are active customers distributed by
-- transaction frequency?
--
-- Activity Definitions:
-- 1-10 transactions   = Low Activity
-- 11-30 transactions  = Moderate Activity
-- 31-60 transactions  = High Activity
-- 61+ transactions    = Very High Activity

WITH customer_activity AS (
    SELECT
        c.customer_id,
        COUNT(t.transaction_id) AS transaction_count
    FROM customers c
    JOIN accounts a
        ON c.customer_id = a.customer_id
    JOIN transactions t
        ON a.account_id = t.account_id
    GROUP BY c.customer_id
),

activity_buckets AS (
    SELECT
        CASE
            WHEN transaction_count BETWEEN 1 AND 10
                THEN 'Low Activity'

            WHEN transaction_count BETWEEN 11 AND 30
                THEN 'Moderate Activity'

            WHEN transaction_count BETWEEN 31 AND 60
                THEN 'High Activity'

            ELSE 'Very High Activity'
        END AS activity_level
    FROM customer_activity
)

SELECT
    activity_level,
    COUNT(*) AS customer_count
FROM activity_buckets
GROUP BY activity_level
ORDER BY
    CASE
        WHEN activity_level = 'Low Activity' THEN 1
        WHEN activity_level = 'Moderate Activity' THEN 2
        WHEN activity_level = 'High Activity' THEN 3
        WHEN activity_level = 'Very High Activity' THEN 4
    END;


/*
============================================================
END OF ANALYSIS
============================================================

Key analytical themes covered:

1. Customer base size and composition
2. Active vs inactive customers
3. Customer segmentation
4. Geographic distribution
5. Age distribution
6. Customer activity by segment
7. Transaction volume and value
8. Monthly transaction trends
9. Debit vs credit behavior
10. Transaction channel usage
11. High-value transactions
12. Product adoption
13. Product activity rates
14. Account type behavior
15. Customer-level transaction activity
16. Customer activity segmentation

Important limitations:

- This is a synthetic dataset created for portfolio purposes.
- Transactions do not contain product_id, so transaction value
  cannot be reliably attributed to individual products.
- A high-value transaction is not automatically suspicious or
  fraudulent; the ₹50,000 threshold is used only for analytical
  segmentation.
- Customer activity is measured using transaction frequency,
  not profitability or customer lifetime value.

============================================================
*/